name: Node.js CI

on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout código
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Instalar dependências
              run: npm install

            - name: Executar Prisma
              run: npm run prisma # Substitua pelo seu comando Prisma, se necessário

            - name: Executar testes
              run: npm run test

            - name: Construir aplicação
              run: npm run build # Substitua pelo comando de construção, se necessário
